// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqmnjokk7Q-zKcmq7FWd7MJgHnhS_HHXQ',
    appId: '1:783996806068:android:7e91cf60683ca8d558c8e1',
    messagingSenderId: '783996806068',
    projectId: 'y-spot-e84ca',
    databaseURL: 'https://y-spot-e84ca-default-rtdb.firebaseio.com',
    storageBucket: 'y-spot-e84ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZc5yFEAwQEC5RtR2go_S-hylMlCb27D0',
    appId: '1:783996806068:ios:74084a14328dd6f558c8e1',
    messagingSenderId: '783996806068',
    projectId: 'y-spot-e84ca',
    databaseURL: 'https://y-spot-e84ca-default-rtdb.firebaseio.com',
    storageBucket: 'y-spot-e84ca.appspot.com',
    androidClientId: '783996806068-11kfpdp5it14vn4sj79njqb3v8idbc67.apps.googleusercontent.com',
    iosClientId: '783996806068-6emitf3cptd4e39v7pskv60nm5dvdaki.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminyspot',
  );

}